# This is a basic workflow to help you get started with Actions

name: build apk

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: git clone
        run: |
          git clone https://github.com/SagerNet/sing-box-for-android
      - name: 构建Java环境
        uses: actions/setup-java@v3
        with:
            distribution: "zulu"
            java-version: "21"
            token: ${{secrets.GIT_TOKEN}}

      - name: flutter build apk
        # 对应 android/app/build.gradle signingConfigs中的配置项
        run: |
          cd ./sing-box-for-android
          ./gradlew assembleRelease
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          # Artifact name
          name: sing-box-for-android
          # A file, directory or wildcard pattern that describes what to upload
          path: .\sing-box-for-android\app\build\outputs\apk\release\
