# This is a basic workflow to help you get started with Actions

name: build apk

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  FLUTTER_VERSION: "3.16.0"
  CORE_VERSION: "1.18.1"
  VERSION: "1.2.7"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-IOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y locate ninja-build libgtk-3-dev libayatana-appindicator3-dev libnotify-dev \
          binutils coreutils desktop-file-utils fakeroot fuse libgdk-pixbuf2.0-dev patchelf python3-pip python3-setuptools squashfs-tools strace util-linux zsync
      - name: clone 
        run: git clone https://github.com/mapleafgo/clash-for-flutter
      - name: Build
        # env:
        #   VERSION: ${{ needs.get-release.outputs.tag_name }}
        run: |
          cd ./clash-for-flutter
          curl -L https://github.com/mapleafgo/cff-core/releases/download/$CORE_VERSION/libclash-$CORE_VERSION-ios.tar.gz -o libclash.tar.gz
          mv build/*.xcframework ios/Frameworks/libclash.xcframework
          flutter build ipa
          cd build/ios/ipa
          mv app-release.ipa clash_for_flutter-$VERSION-ios.ipa
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          # Artifact name
          name: clash_for_flutter-$VERSION-ios
          # A file, directory or wildcard pattern that describes what to upload
          path: clash-for-flutter/build/ios/ipa/*.ipa
