name: Compile and Upload localsend-rs

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: zpp0196/localsend-rs
          ref: main
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
          override: true
      - run: cargo build --release
      - uses: actions/upload-artifact@v3
        with:
          name: localsend-rs-windows
          path: target/release/localsend-rs*
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          override: true
      - run: cargo build --release
      - uses: actions/upload-artifact@v3
        with:
          name: localsend-rs-macos
          path: target/release/localsend-rs*
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - run: cargo build --release
      - uses: actions/upload-artifact@v3
        with:
          name: localsend-rs-macos
          path: target/release/localsend-rs*
