name: Build flutter rss

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build for iOS and Android
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        repository: yang991178/fluent-reader-lite
        ref: master

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
<<<<<<< HEAD
        # flutter-version: 3.19.0

=======
        # flutter-version: 2.x
    #- name: git clone
      #run: git clone https://github.com/yang991178/fluent-reader-lite
>>>>>>> 21baacb41088109a4181388e9f0132c2ef44081d
    - name: Get Dependencies
      run: flutter pub get

    - name: Build for Android
      run: flutter build apk

    - name: Build for iOS
      run: flutter build ios --release --no-codesign
    - name: create ipa
      run: |
        mkdir Payload
        cp -R build/ios/iphoneos/Runner.app Payload/
        zip -r flutter-reader.ipa Payload
    - name: Archive iOS App
      uses: actions/upload-artifact@v2
      with:
        name: flutter-reader-ios
        path: ./flutter-reader.ipa
    



