name: Build FlareDNS

on:
  workflow_dispatch:                # 手动触发
    inputs:
      build_type:
        description: "构建类型"
        required: true
        default: "Release"

jobs:

  build-ios:
    name: Build iOS App (No Signing)
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: missuo/FlareDNS
          fetch-depth: 0

      - name: Select Xcode
        run: sudo xcode-select -s "/Applications/Xcode_26.1.app"

      - name: Build iOS target
        run: |
          xcodebuild -list
          xcodebuild \
          -project "FlareDNS.xcodeproj" \
          -scheme "FlareDNS-iOS" \
          -configuration ${{ github.event.inputs.build_type }} \
          -sdk iphoneos \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGN_IDENTITY="" \
          PROVISIONING_PROFILE_SPECIFIER="" \
          SKIP_INSTALL=NO \
          archive \
          -archivePath build/ios/FlareDNS.xcarchive
      - name: Export app and zip
        run: |
          mkdir -p output/ios
          cp -R build/ios/FlareDNS.xcarchive/Products/Applications/*.app output/ios/
          cd output/ios && zip -r FlareDNS_iOS.zip *.app
      - uses: actions/upload-artifact@v4
        with:
          name: AngelLive-iOS
          path: output/ios/*.zip
