# This is a basic workflow to help you get started with Actions

name: build AllLive

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  FLUTTER_VERSION: "3.16.0"
  CORE_VERSION: "1.18.1"
  VERSION: "1.10.2"
  NAME: "Playboy"
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
    - name: git clone 
      run: git clone https://github.com/xiaoyaocz/AllLive 
    - name: Restore NuGet packages
      run: |
        cd AllLive
        nuget restore AllLive.sln
    - name: Build UWP Appx
      run: |
        cd AllLive
        msbuild /p:Configuration=Release /p:Platform=x86 /m /nologo /p:AppxBundlePlatforms="x86|x64|ARM" /p:AppxBundle=Always /p:OutputPath=./release AllLive.sln
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        # Artifact name
        name: AllLive
        # A file, directory or wildcard pattern that describes what to upload
        path: AllLive/release/*.appx

          
      
