# This is a basic workflow to help you get started with Actions

name: AwemeLike

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  appname: AwemeLike
  version: 0.0.1
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: clone 
        run: git clone https://github.com/ZZZZou/AwemeLike

      # Runs a set of commands using the runners shell
      - name: build
        run: |
          cd ${{ env.appname }}
          xcodebuild clean # -workspace $PWD/${{ env.appname }}.xcodeproj -scheme ${{ env.appname }} -configuration Release
          xcodebuild archive -workspace $PWD/${{ env.appname }}.xcworkspace -scheme ${{ env.appname }} -archivePath $PWD/build/${{ env.appname }}.xcarchive # archive
          # xcodebuild -exportArchive -archivePath build/${{ env.appname }}.xcarchive -exportPath build -exportOptionsPlist ${{ env.appname }}/YoutubeDL-Info.plist
          xcrun -sdk iphoneos PackageApplication -v $PWD/build/Release-iphoneos/${{ env.appname }}.app -o $PWD/${{ env.appname }}-${{ env.version }}.ipa
      - name: upload
        uses: actions/upload-artifact@v4.2.0
        with:
          # Artifact name
          name: ${{ env.appname }}-${{ env.version }}
          # A file, directory or wildcard pattern that describes what to upload
          path: ${{ env.appname }}/${{ env.appname }}-${{ env.version }}.ipa