# Original idea by @ISnackable. Thanks to him for handling the hardest parts!
# https://github.com/ISnackable/YTCubePlus/blob/main/.github/workflows/Build.yml

name: Build and Release uYouEnhanced
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      sdk_version:
        description: "iOS SDK version to be used during build"
        default: "16.4"
        required: true
        type: string
      uyou_version:
        description: "The version of uYou"
        default: "3.0.3"
        required: true
        type: string
      decrypted_youtube_url:
        description: "The direct URL to the decrypted YouTube ipa"
        default: ""
        required: true
        type: string
      bundle_id:
        description: "Modify the bundle ID. Not recommended"
        default: "com.google.ios.youtube"
        required: true
        type: string
      app_name:
        description: "Modify the name of the app on the Home Screen. Not recommended"
        default: "YouTube"
        required: true
        type: string
      create_release:
        description: "Create a draft release"
        default: true
        required: false
        type: boolean
      upload_artifact:
        description: "Upload Artifact"
        default: true
        required: false
        type: boolean
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build uYouEnhanced
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4.1.1
        with:
          path: main
          submodules: recursive

      - name: Install Dependencies
        run: brew install ldid dpkg make

      - name: Set PATH environment variable
        run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH 

      - name: Setup Theos
        uses: actions/checkout@v4.1.1
        with:
          repository: theos/theos
          ref: master
          path: theos
          submodules: recursive
      
      - name: SDK Caching
        id: SDK
        uses: actions/cache@v4.0.2
        env:
          cache-name: iOS-${{ inputs.sdk_version }}-SDK
        with:
          path: theos/sdks/
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}
      - name: git clone
        run: git clone https://github.com/arichornlover/uYouEnhanced
      - name: Download iOS SDK
        if: steps.SDK.outputs.cache-hit != 'true'
        run: |
          cd ${{ github.workspace }}/uYouEnhanced/main
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/arichornlover/sdks/
          cd sdks
          git sparse-checkout set --no-cone iPhoneOS${{ inputs.sdk_version }}.sdk
          git checkout
          mv *.sdk $THEOS/sdks
        env:
          THEOS: ${{ github.workspace }}/uYouEnhanced/theos

      - name: Setup Theos Jailed
        uses: actions/checkout@v4.1.1
        with:
          repository: qnblackcat/theos-jailed
          ref: master
          path: theos-jailed
          submodules: recursive

      - name: Install Theos Jailed
        run: |
          cd ${{ github.workspace }}/uYouEnhanced/main
          ./theos-jailed/install
        env:
          THEOS: ${{ github.workspace }}/uYouEnhanced/theos

      - name: Prepare YouTube iPA
        id: prepare_youtube
        run: |
          cd ${{ github.workspace }}/uYouEnhanced/main
          wget "$YOUTUBE_URL" --no-verbose -O main/YouTube.ipa
          mv YouTube.ipa YouTube.zip
          unzip -q YouTube.zip
          youtube_version=$(defaults read "$(pwd)/Payload/YouTube.app/Info" CFBundleVersion)
          echo "==> YouTube v$youtube_version downloaded!"
          sed -i '' "17s#.*#YOUTUBE_VERSION = ${youtube_version}#g" Makefile
          echo "youtube_version=${youtube_version}" >> $GITHUB_OUTPUT

        env:
          THEOS: ${{ github.workspace }}/uYouEnhanced/theos
          YOUTUBE_URL: ${{ inputs.decrypted_youtube_url }}

      - name: Fix compiling & Build Package
        id: build_package
        run: |
          cd ${{ github.workspace }}/uYouEnhanced/main
          sed -i '' "27s#.*#BUNDLE_ID = ${{ env.BUNDLE_ID }}#g" Makefile
          sed -i '' "26s#.*#DISPLAY_NAME = ${{ env.APP_NAME }}#g" Makefile          
          make package THEOS_PACKAGE_SCHEME=rootless IPA=Payload/YouTube.app FINALPACKAGE=1
          echo "package=$(ls -t packages | head -n1)" >>$GITHUB_OUTPUT
          echo -e "==> \033[1mSHASUM256: $(shasum -a 256 packages/*.ipa | cut -f1 -d' ')\033[0m"
          echo -e "==> \033[1mBundle ID: ${{ env.BUNDLE_ID }}\033[0m"

        env:
          THEOS: ${{ github.workspace }}/uYouEnhanced/theos
          UYOU_VERSION: ${{ inputs.uyou_version }}
          BUNDLE_ID: ${{ inputs.bundle_id }}
          APP_NAME: ${{ inputs.app_name }}

      - name: Upload Artifact
        if: ${{ inputs.upload_artifact }}
        uses: actions/upload-artifact@v4.3.1
        env:
          UYOU_VERSION: ${{ inputs.uyou_version }}
          YOUTUBE_VERSION: ${{ steps.prepare_youtube.outputs.youtube_version }}
        with:
          name: uYouEnhanced_${{ env.YOUTUBE_VERSION }}_${{ env.UYOU_VERSION }}
          path: ${{ github.workspace }}/uYouEnhanced/main/packages/${{ steps.build_package.outputs.package }}
          if-no-files-found: error
