# This is a basic workflow to help you get started with Actions

name: build coriander_player

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  FLUTTER_VERSION: "3.16.0"
  CORE_VERSION: "1.18.1"
  VERSION: "0.0.2"
  NAME: "coriander_player"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [android, ios, web]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.13.0
        with:
          # The Flutter version to make available on the path
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Install dependencies
        run: |
          git clone https://github.com/Ferry-200/coriander_player
          cd ${{ env.NAME }}
          flutter pub get

      - name: Build ${{ matrix.platform }}
        run: |
          cd ${{ env.NAME }}
          if [ "${{ matrix.platform }}" = "android" ]; then
            flutter build apk
          elif [ "${{ matrix.platform }}" = "ios" ]; then
            flutter build ios --no-codesign
          elif [ "${{ matrix.platform }}" = "web" ]; then
            flutter build web
          fi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.NAME }}-${{ env.VERSION }}-${{ matrix.platform }}-build
          path: |
            ${{ env.NAME }}/build/**/*.apk
            ${{ env.NAME }}/build/**/*.ipa
            ${{ env.NAME }}/build/web/**
          if-no-files-found: ignore
