# This is a basic workflow to help you get started with Actions

name: build Playboy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  FLUTTER_VERSION: "3.16.0"
  CORE_VERSION: "1.18.1"
  VERSION: "1.10.2"
  NAME: "Playboy"
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.13.0
        with:
          # The Flutter version to make available on the path
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Install dependencies
        run: |
          git clone https://github.com/Playboy-Player/Playboy
          cd ${{ env.NAME }}
          flutter pub get

      - name: Build ${{ matrix.platform }}
        run: |
          cd ${{ env.NAME }}
          if [ "${{ matrix.os }}" = "macos-latest" ]; then
            flutter build macos
          elif [ "${{ matrix.os }}" = "windows-latest" ]; then
            flutter build windows
          elif [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            flutter build linux
          fi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.NAME }}-${{ env.VERSION }}-${{ matrix.os }}-build
          path: |
            ${{ env.NAME }}/build/**/*.dmg
            ${{ env.NAME }}/build/**/*.exe
            ${{ env.NAME }}/build/web/**
          if-no-files-found: ignore
