name: Build Leplayer

on:
  workflow_dispatch:
  # 手动触发
    inputs:
      build_type:
        description: "构建类型"
        required: true
        default: "Release"
      tags:
        description: '指定 FlareDNS 版本号（如 v1.0.0 或 latest）'
        required: true
        default: '1.2.0'

jobs:

  build-ios:
    name: Build Leplayer TVOS App (No Signing)
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: leisurehuang/Leplayer
          fetch-depth: 0

      - name: Select Xcode
        run: sudo xcode-select -s "/Applications/Xcode_26.1.app"
      - name: pod install
        run:  pod install
      - name: Build tvOS target
        run: |
          xcodebuild -list
          xcodebuild \
          -project "Leplayer.xcodeproj" \
          -scheme "Leplayer" \
          -configuration ${{ github.event.inputs.build_type }} \
          -sdk tvos \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGN_IDENTITY="" \
          PROVISIONING_PROFILE_SPECIFIER="" \
          SKIP_INSTALL=NO \
          archive \
          -archivePath build/tvos/Leplayer.xcarchive
      - name: Export app and zip
        run: |
          mkdir -p Payload
          cp -r build/tvos/Leplayer.xcarchive/Products/Applications/*.app Payload
          zip -r "Leplayer-tvOS-${{ github.event.inputs.tags }}.ipa" Payload/
      - uses: actions/upload-artifact@v4
        with:
          name: Leplayer-tvOS-${{ github.event.inputs.tags }}
          path: "Leplayer-tvOS-${{ github.event.inputs.tags }}.ipa"
      - name: 创建 Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "Leplayer-${{ github.event.inputs.tags }}"
          name: "Leplayer-${{ github.event.inputs.tags }}"
          files: "Leplayer-tvOS-${{ github.event.inputs.tags }}.ipa"
          # draft: false
          # prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
