name: Build Orange-Cloud

on:
  workflow_dispatch:
  # 手动触发
    inputs:
      build_type:
        description: "构建类型"
        required: true
        default: "Release"
      tags:
        description: '指定 orange-cloud-ios 版本号（如 v1.0.0 或 latest）'
        required: true
        default: '1.9.0'
      android-tags:
        description: '指定 orange-cloud-android 版本号（如 v1.0.0 或 latest）'
        required: true
        default: '1.7.1'

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: chen2he/orange-cloud
        # fetch-depth: 0
        # submodules: true

    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    - name: Setup gradle
      uses: gradle/actions/setup-gradle@v3
    - name: gradlew assembleOssDebug
      run: |
        cd apps/android
        echo ${{ secrets.MYAPP_KEYSTORE_BASE64 }} | base64 --decode > app/${{ secrets.MYAPP_UPLOAD_STORE_FILE }}
        chmod +x ./gradlew
        ./gradlew :app:assembleOssDebug # -PMYAPP_UPLOAD_STORE_FILE='app/${{ secrets.MYAPP_UPLOAD_STORE_FILE }}' -PMYAPP_UPLOAD_KEY_ALIAS='${{ secrets.MYAPP_UPLOAD_KEY_ALIAS }}' -PMYAPP_UPLOAD_STORE_PASSWORD='${{ secrets.MYAPP_UPLOAD_STORE_PASSWORD }}' -PMYAPP_UPLOAD_KEY_PASSWORD='${{ secrets.MYAPP_UPLOAD_KEY_PASSWORD }}'

    # - name: Sign app APK
    #   id: sign_app
    #   uses: ilharp/sign-android-release@nightly
    #   with:
    #     releaseDir: app/build/outputs/apk/release
    #     signingKey: ${{ secrets.SIGNING_KEY }}
    #     keyAlias: ${{ secrets.ALIAS }}
    #     keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
    #     keyPassword: ${{ secrets.KEY_PASSWORD }}

    # - name: Upload Artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: Orange-Cloud-${{ github.event.inputs.tags }}
    #     path: apps/android/app/build/outputs/apk/oss/debug/*.apk
        # if-no-files-found: error
        # retention-days: 20
    - name: 创建 Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: "Orange-Cloud-${{ github.event.inputs.tags }}"
        name: "Orange-Cloud-${{ github.event.inputs.tags }}"
        files: apps/android/app/build/outputs/apk/oss/debug/*.apk
        # draft: false
        # prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-ios:
    name: Build iOS App (No Signing)
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: chen2he/orange-cloud
          fetch-depth: 0

      - name: Select Xcode
        run: sudo xcode-select -s "/Applications/Xcode.app"
      - name: Enable OPENSOURCE_UNLOCKED
        run: |
          PBX="apps/ios/Orange Cloud/Orange Cloud.xcodeproj/project.pbxproj"
      
          sed -i '' \
            's/SWIFT_ACTIVE_COMPILATION_CONDITIONS = DEBUG;/SWIFT_ACTIVE_COMPILATION_CONDITIONS = "DEBUG OPENSOURCE_UNLOCKED";/g' \
            "$PBX"
      
          sed -i '' \
            's/SWIFT_ACTIVE_COMPILATION_CONDITIONS = RELEASE;/SWIFT_ACTIVE_COMPILATION_CONDITIONS = OPENSOURCE_UNLOCKED;/g' \
            "$PBX"
      - name: Build iOS target
        run: |
          cd "apps/ios/Orange Cloud/"
          xcodebuild -list
          xcodebuild \
          -project "Orange Cloud.xcodeproj" \
          -scheme "Orange Cloud" \
          -configuration ${{ github.event.inputs.build_type }} \
          -destination "generic/platform=iOS" \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGN_IDENTITY="" \
          PROVISIONING_PROFILE_SPECIFIER="" \
          SKIP_INSTALL=NO \
          archive \
          -archivePath build/ios/Orange-Cloud.xcarchive
          
          xcodebuild \
          -project "Orange Cloud.xcodeproj" \
          -scheme "Orange Cloud Watch Watch App" \
          -configuration ${{ github.event.inputs.build_type }} \
          -destination "generic/platform=watchOS" \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGN_IDENTITY="" \
          PROVISIONING_PROFILE_SPECIFIER="" \
          SKIP_INSTALL=NO \
          archive \
          -archivePath build/watchos/Orange-Cloud.xcarchive
      - name: Export app and zip
        run: |
          cd "apps/ios/Orange Cloud/"
          mkdir -p Payload
          cp -r build/ios/Orange-Cloud.xcarchive/Products/Applications/*.app Payload
          zip -r "Orange-Cloud-ios-${{ github.event.inputs.tags }}.ipa" Payload/
          rm -rf Payload/ && mkdir -p Payload
          cp -r build/watchos/Orange-Cloud.xcarchive/Products/Applications/*.app Payload
          zip -r "Orange-Cloud-watchos-${{ github.event.inputs.tags }}.ipa" Payload/
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: Orange-Cloud-${{ github.event.inputs.tags }}
      #     path: "apps/ios/Orange Cloud/Orange-Cloud-${{ github.event.inputs.tags }}.ipa"
      - name: 创建 Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "Orange-Cloud-${{ github.event.inputs.tags }}"
          name: "Orange-Cloud-${{ github.event.inputs.tags }}"
          files: "apps/ios/Orange Cloud/*.ipa"
          # draft: false
          # prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
