name: Build & Release reader Multi-Platform

on:
  workflow_dispatch:
    inputs:
      tags:
        description: '指定 reader 版本号（如 v2.8.4 或 latest）'
        required: true
        default: 'latest'
jobs:
  build-reader:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: chenglu1129/reader-spring-vue

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'
      - name: Build web
        run: cd web && npm install && npm run build
      - name: Build Java
        run:
          mv ./web/dist ./src/main/resources/web && ./gradlew assemble --info && mv ./build/libs/*.jar ./reader.jar
      - name: 创建 Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "reader-${{ github.event.inputs.tags }}"
          name: "reader-${{ github.event.inputs.tags }}"
          files: "./reader.jar"
          # draft: false
          # prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
